### PR TITLE
Added zonal_statistics notebook

### PR DESCRIPTION
**Pull request by thuydotm**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. A few things:

1. Can you make the links to NASADEM, Sneitnel-2, and Ersri 10m landcover point to the pages in https://planetarycomputer.microsoft.com/catalog? Those link to the the sources and more.
2. When defining `nasadem_data = ...` you have a `.where(lambda x: x > 0, other=np.nan)`. Is that necessary?
3. For `sentinel_data = ...` you take a `.median(dim="time")` over the 15 items in the time dimension. Can you add a sentinels to the preceeding paragraph explaining why we do that (we need to collapse over time, and we take a median to remove clouds. Maybe link to the cloud-free mosaic notebook)
4. I don't understand why you need a `.median(dim="time")` for the `io_lulc` dataarray. I see that without it, the size along the `time` dimension is 2, but the coordinates is just `2020-06-01T00:00:00` repeated. For reference, this dataset *should* have just the single time, since it's derived from a mosaic of many images. Do you know why the size along `time` is 2?
5. I find the colorbars hard to read, since they're separate from the image they apply to. Can you place the colorbar axis next to the image axis for the two with colorbars?
6. What version of xarray is required for this? With the version on staging, I see `TypeError: stats() got an unexpected keyword argument 'stats_funcs'
`.
7. Can you `compute` and print out `quantile_zones`? I think that'll help make clear that we're grouping by integers (other than the NaNs on the edges)
8. Under "Compute zonal statistics" you have " In this example, use the Sentinel data as a value raster." which makes it sound like we're just passing the sentinel data in, which isn't right. It'd be better to say that we're using NDVI *computed from* Sentinel data.
9. Can one of matplotlib's qualitative colormaps instead of `rainbow` for the zones? Maybe `Set1`.
10. The IO-LULC COGs define a colormap. Can you use that? https://planetarycomputer.microsoft.com/dataset/io-lulc#Example-Notebook has an example.

**Comment by thuydotm** [comment]
Thanks for all the comments. I'll make the wording changes, update the data links and try to make the plots look better.

> 2. When defining `nasadem_data = ...` you have a `.where(lambda x: x > 0, other=np.nan)`. Is that necessary?

Not really, I'll remove this.

> 4. I don't understand why you need a `.median(dim="time")` for the `io_lulc` dataarray. I see that without it, the size along the `time` dimension is 2, but the coordinates is just `2020-06-01T00:00:00` repeated. For reference, this dataset _should_ have just the single time, since it's derived from a mosaic of many images. Do you know why the size along `time` is 2?

`io_lulc_items` contains 4 items: `['15S-2020', '15R-2020', '14S-2020', '14R-2020']`. Without any specified values set to function parameters, `stackstac.stack` should create a 4D cube of (time, band, y, x) where time is 4. Since we set `bounds=nasadem_data.spec.bounds`, it only contains 2 items that match this condition, `15S-2020` and `14S-2020`. That's why time is 2. I think doing a median over time dimension (or some other operations, e.g: min, max, mean) is necessary to eliminate the time dimension.

> 6. What version of xarray is required for this? With the version on staging, I see `TypeError: stats() got an unexpected keyword argument 'stats_funcs' `.

You can run it with lastest release of 0.2.7

**Comment by TomAugspurger** [comment]
Thanks for that link.

It seems more natural to me for the dataarray to one time coordinate per unique `datetime` in the STAC items. Could you open an issue on stackstac with a small example to combine duplicate `time` coordinates would would be accepted?

In the meantime, perhaps `.fillna(dim="time").isel(time=-1)` is better than `median`. I think that the median is more computationally expensive than just taking the only non-nan value.

**Comment by thuydotm** [comment]
Thanks, I updated the notebook and opened an issue here: https://github.com/gjoseph92/stackstac/issues/66

**Comment by TomAugspurger** [comment]
Thanks @thuydotm.

For the landcover data, you currently have `.fillna(0).isel(time=-1)`. I don't think that's quite what we want. I think that `.fillna("time").isel(time=-1)` is what we want. IIUC only some subset of the x/y values will be non-NA for each `time` slice. By filling NA values forward in time, the last time time slice should have the non-NA values (if there are any).

Last thing: I notice that `xrspatial.zonal._stats_dask` eagerly does some computation. Glancing at the source, it may be https://github.com/makepath/xarray-spatial/blob/d6ace73f7af459906eda232578693d9ea8a0ff32/xrspatial/zonal.py#L132. Are the unique zones necessary, or can that computation be delayed until the user calls `.compute()`? If it's unavoidable, it's nice to provide users the option to specify the `unique_zones` as a keyword.  For datasets like landcover or even our derived binned elevation data, we already know the unique values ahead of time.

**Comment by TomAugspurger** [comment]
And I think it'd be interesting just to show a short example grouping the NDVI values by the IO landcover raster:

```python
stats = zonal_stats(landcover_data, ndvi_values, stats_funcs=["mean", "count"])
stats.compute().assign(zone=lambda df: df.zone.map(landcover_data_classes)).set_index("zone")
```

That lets you quickly see the average NDVI by the various classes.

**Comment by TomAugspurger** [comment]
Just to make sure we're on the same page here about the NA / `time` issue. Right now you just have `.isel(-1)`, but I think the `ffill` may be necessary.

My understanding is that a specific x/y coordinate will only have one non-NA value: the specific `time` position for that item. If consider just an array with `('time', 'x')` that would be:

```python
In [1]: import xarray as xr
In [2]: import numpy as np

In [3]: a = xr.DataArray(np.array([[np.nan, 1], [2, np.nan]]), dims=("time", "x"))

In [4]: a
Out[4]:
<xarray.DataArray (time: 2, x: 2)>
array([[nan,  1.],
       [ 2., nan]])
Dimensions without coordinates: time, x
```

We want to aggregating over `time` by taking the first / last / only non-NA value. SO we fill non-NA values forward:

```
In [5]: a.ffill("time")
Out[5]:
<xarray.DataArray (time: 2, x: 2)>
array([[nan,  1.],
       [ 2.,  1.]])
Dimensions without coordinates: time, x
```

And then select the last item:

```
In [6]: a.ffill("time").isel(time=-1)
Out[6]:
<xarray.DataArray (x: 2)>
array([2., 1.])
Dimensions without coordinates: x
```

Does that sound right to you? I haven't actually checked that the data from stackstac is actually like that, so we should verify that.

**Comment by thuydotm** [comment]
Thanks for the explanation. I checked the actual data and it contains all NaNs for the first time slice. In contrast, the last time slice (i.e the second slice in this example as we only have 2 slices) contains valid values only. So `.isel(-1)` works in this specific case. But you're right about filling forward the non-NA values. I was confused with the `fillna` so didn't add this step yet. Apply `ffill` to the data now.

**Comment by thuydotm** [comment]
I'll let you know the version of xarray-spatial once we have it release.

**Comment by TomAugspurger** [comment]
OK thanks. I wonder if only the last time slice having non-NaN values is always the case when there are repeated `time` values, or if that's just specific to this dataset / slicing. I think having the ffilll is safer, in case others are copying this example for other datasets / regions.

**Comment by TomAugspurger** [comment]
> I'll let you know the version of xarray-spatial once we have it release.

Is there something in this notebook requiring an unreleased xarray-spatial? I ran it on the staging Hub with 0.2.7 and things worked fine.

**Comment by TomAugspurger** [comment]
Seems like `zone_ids` might be the new piece. Again, let's not block this notebook waiting for a release. We can update it later.

I'm going to push an update to this notebook shortly shifting some things around. Apologies for the wasted effort, but I think the notebook will flow more smoothly if we focus initially on two datasets.

1. I/O landcover as the `zones` raster
2. NDVI from sentinel as the `values` raster

The three datasets were confusing me at the start, since we're also emphasizing that zonal stats involves *two* rasters: the zones and values.

I might also remove / simplify the `plot_imgs` since we'll only have the two datasets. I worry about having giant blocks of code in these notebooks.

I will bring the discretized NASADEM back at the end for the zonal_crosstab, since that requires two discrete rasters.

**Comment by thuydotm** [comment]
Okay, that sounds reasonable. About `crosstab`, the input `values` raster can be either 2D or 3D. It's just an idea now that, in case you don't want to bring a new dataset, I think we can probably create a 3D NDVI values raster of `(time, y, x)` where the time dimension is 12 to cover 12 months of a year for example. And we can analyze the average NDVI of each landcover class over the year. This would require `crosstab` to support different aggregation methods for 3D case. Currently, only `count` supported for 3D rasters. If this makes sense to you, we can add this feature to xrspatial and update the notebook later.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
