### PR TITLE
GLM + QPE Example Notebooks

### PR DESCRIPTION
**Pull request by pholleway**
- Added QPE Example Notebook
- Added GLM Example Notebook

### CODE REVIEW

**Comment by pholleway** [comment]
@TomAugspurger Here are the GLM & QPE examples notebooks. Feel free to use whichever notebook for GLM you prefer. I think a combination of both down the road would be great. 

Also, I'm about to add the notebooks at [PlanetaryComputerDataCatalog](https://github.com/microsoft/PlanetaryComputerDataCatalog)/[etl](https://github.com/microsoft/PlanetaryComputerDataCatalog/tree/develop/etl)/[config](https://github.com/microsoft/PlanetaryComputerDataCatalog/tree/develop/etl/config)/codefiles_urls.txt

**Comment by TomAugspurger** [comment]
Very cool, thanks! I'll merge in the GLM stuff for working with many files.

**Comment by TomAugspurger** [comment]
Thanks!

**Comment by pholleway** [comment]
> Very cool, thanks! I'll merge in the GLM stuff for working with many files.

Sounds good. Thanks, @TomAugspurger.

**Pull request merged**
