### PR TITLE
noaa-nclimgrid example notebook

### PR DESCRIPTION
**Pull request by pholleway**
- Added example notebook for noaa nclimgrid
- API will need to be updated to production

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks!

I'm seeing some strange data when I run this on the (staging) Hub. Here's the first plot.

image

Where did you run this? I'm wondering if it could be a version issue.

**Comment by pholleway** [comment]
@TomAugspurger  Note: There was a bug introduced in rasterio 1.3.0 that may be related. https://github.com/rasterio/rasterio/issues/2511

**Comment by TomAugspurger** [comment]
Yep, that's probably it. I'm on 1.3.0. I'm planning to update the container images this week anyway.

**Comment by TomAugspurger** [comment]
Thanks @pholleyway, things are working with rasterio>=1.3.0.

I pushed a small change to avoid re-using the `plt` variable name.

**Comment by pholleway** [comment]
Sounds good. Thanks, @TomAugspurger.

**Pull request merged**
