### PR TITLE
Add 3dep-seamless example notebook

### PR DESCRIPTION
**Pull request by gadomski**
PDF version here: [3dep-seamless-example.pdf](https://github.com/microsoft/PlanetaryComputerExamples/files/6779031/3dep-seamless-example.pdf)

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'll push a fix for the linting issue with a few other changes.

**Comment by gadomski** [comment]
Ok, sorry about that -- working on setting up linting in notebooks meow.

**Comment by mmcfarland** [comment]
>  working on setting up linting

Ah, that's my bad - I should have given you a heads up on that.

If you install `pre-commit`, running `pre-commit run --all-files` will get you set up locally.

**Comment by TomAugspurger** [comment]
Updated some of the wording, linked to the entry in our datacatlog, using stackstac to load into xarray, and updated the plotting slightly.

Thanks @gadomski!

**Pull request merged**
