### PR TITLE
Add surface_analysis notebook

### PR DESCRIPTION
**Pull request by tcmetzger**
This PR adds the surface_analysis notebook to the tutorials folder.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. Some comments below:

1. "Azure Storage" -> "Azure Blob Storage"
2. Use `pystac_client` rather than `satsearch`
3. While running the example, I noticed that the operations like `hillshade` weren't parallelizing too well. I think that was primarily caused by small chunks in the Dask array (8 Mb). Can you add `chunksize=2048` to the `stackstac.stack` call and link to https://docs.dask.org/en/latest/array-best-practices.html#select-a-good-chunk-size?
4. I think it's worth (re)-emphasizing that all of the xrspatial functions are just returning DataArrays. Maybe print out the `elevation_img` DataArray prior to plotting it? And then in the wrapup under "Next steps" you can again mention that these return DataArrays which can be used in downstream analysis.
5. (xarrap-spatial API nitpick): All of the stuff around setting up the Canvas feels a bit awkward
```
# get full extent of raster
full_extent = (
    elevation_raster.coords["x"].min().item(),
    elevation_raster.coords["y"].min().item(),
    elevation_raster.coords["x"].max().item(),
    elevation_raster.coords["y"].max().item(),
)

# get ranges
x_range = (full_extent[0], full_extent[2])
y_range = (full_extent[1], full_extent[3])

# set width and height
W = 750
H = height_implied_by_aspect_ratio(W, x_range, y_range)

cvs = ds.Canvas(plot_width=W, plot_height=H, x_range=x_range, y_range=y_range)
```

That's a lot of typing for what's essentially "(spatially) resample this DataArray" to this new size. It'd be nice if xarray-spatial add a higher-level API to make that easier. Something like

```python
def resample_spatial(ds=None, x=None, y=None, *, width=None, height=None):
    """
    Spatially resample a DataArray to a new size.

    Notes about dimensions, coordinates, how width / height are handled.

    Examples
    ----------
    >>> elevation_small = resample_spatial(elevation_raster, x="x", y="y", width=750)
    """
```

Implementation-wise that would look very similar to the code from the notebook. Determine the new coordinate bounds, get the width and height for datashader's `Canvas`. There would be some things to figure with how dimensions are passed in (separate data arrays like `ds['x'], ds['y']` vs. a single DataArray and names like `ds, 'x', 'y'), but I think it'd be helpful. Any thoughts on that?

**Comment by thuydotm** [comment]
Thanks. The notebook is updated as suggested. A function called `canvas_like` is being added to xarray-spatial to wrap all resampling steps using in the notebook.

- [x] "Azure Storage" -> "Azure Blob Storage"
- [x] Use `pystac_client` rather than `satsearch`
- [x] Call `planetary_computer.sign(item)` on all the items prior to stacking them
- [x] Add `chunksize=2048` to the `stackstac.stack` call and link to https://docs.dask.org/en/latest/array-best-practices.html#select-a-good-chunk-size
- [x] (re)-emphasizing that all of the xrspatial functions are just returning DataArrays
- [x] (xarrap-spatial API nitpick) Add a higher-level API that uses Datashader internally to resample a DataArray: https://github.com/makepath/xarray-spatial/pull/539

**Comment by TomAugspurger** [comment]
I notice that the file is now 9.7Mb (dunno if it was before) which would make it the largest we have.

Do you know why it's so large? Are you able to cut that down to roughly <3Mb to be in line with the other notebooks?

**Comment by thuydotm** [comment]
Thanks for the comments. The resampling section is revert to coding block instead of using `canvas_like` function. The large file caused by the size of canvas/images to be displayed. I've reduced image width to 300 instead of 400 and the file is about 3.7Mb now.

**Comment by TomAugspurger** [comment]
Great, thanks!

**Pull request merged**
