### PR TITLE
Proximity tools

### PR DESCRIPTION
**Pull request by thuydotm**

### CODE REVIEW

**Comment by thuydotm** [comment]
This notebook is ready for review. Please run with the latest version of xarray-spatial of 0.2.8.

**Comment by TomAugspurger** [comment]
Thanks, I'll take a look.

I just updated staging with xarray-spatial 0.2.8

**Comment by TomAugspurger** [comment]
Looking at the task graphs, I'm a bit surprised to see a bottleneck in the middle of the graph:

```
>>> extent_proximity.data.visualize(rankdir="LR", optimize_graph=True)
```

image

I might rephrase the bit around Dask and `max_distance`. I hesitate to document a limitation like that here, since we're so far from the source it'll go stale if / when it's fixed upstream (the API docs for proximity might be more appropriate).

Is that expected / necessary?

---

I might reword the section around

**Comment by thuydotm** [comment]
This is expected. The bottleneck is from the way we do `map_overlap` I believe https://github.com/makepath/xarray-spatial/blob/master/xrspatial/proximity.py#L634 

I tried to re-order the function parameters, to use *args, and tried several other options to move things around to preserve the shape but when calling .compute(), the function returned the wrong results. For example, this way we get correct shape but the results go weird.

```python
out = raster.data.map_overlap(
        func=_process_numpy,
        x_coords=xs,
        y_coords=ys,
        target_values=target_values,
        max_distance=max_distance,
        distance_metric=distance_metric,
        process_mode=process_mode,
        depth=(pad_y, pad_x),
        boundary=np.nan,
        meta=np.array(()),
    )
```

In the current code, having `chunks=raster.shape` is necessary to make sure we get a 2d data array but it also set the chunk size equal to the raster shape. Thus having `.rechunk(raster.chunks)` is also necessary I think.

**Comment by TomAugspurger** [comment]
Hmm, so in effect that means we get no parallelism, even when `target_values` is small or `max_distance` is specified, correct?

> In the current code, having chunks=raster.shape is necessary to make sure we get a 2d data array but it also set the chunk size equal to the raster shape.

I won't have time to look into this, but can you clarify where the issue lies? With something like this, we do have matching shapes / chunks:

```python
>>> extent_data.data.map_overlap(lambda x: x, depth=10, trim=False).chunks == extent_data.chunks
True
```

**Comment by TomAugspurger** [comment]
We just spoke about the parallelism issue. @thuydotm has a work-in-progress change to xrspatial.proximity that fixes the bottleneck. That will go into xrspatial, no changes required here.

**Pull request merged**
