### PR TITLE
Added cloudless mosaic tutorial

### PR DESCRIPTION
**Pull request by TomAugspurger**
This adds the cloudless mosaic tutorial that @thuydotm & others put together (cc @brendancol, @lex-c, @marcozimmermannpm).

nbviewer link: https://nbviewer.jupyter.org/github/microsoft/PlanetaryComputerExamples/blob/1d84d4af6fc2468507c6ba8cad5a5f8d0aa17540/tutorials/cloudless-mosaic-sentinel2.ipynb

A few changes:

1. Move to our standard AOI above Redmond, Washington used elsewhere in the docs
2. Expand the scope a bit (2016 - 2020) and increase the resolution (reading in the highest overview I think)
3. Make sure to manually convert 0 to np.nan since, our COGs on S2 don't have the `nodata` value set (yet) 😢
4. Show a composite over all the images
5. Show a per-month set of composites

Overall, I think this is pretty slick demo!

---

One minor API papercut with xarray-spatial: Consider the following operation from the notebook where we compute the `ms.true_color` for each image in the dataset. `true_color` expects red, green, and blue arrays, so the `time` dimension is getting in the way. In the notebook, I manually iterate over the first dimension of the array (time) and then concatenate them back together:

```python
monthly = data.groupby("time.month").median().compute()
images = [
    ms.true_color(*x) for x in monthly
]
images = xr.concat(images, dim="time")
```

Do you have suggestions on how to make that cleaner? I *think* that `xarray.apply_ufunc`  might be an option, but it expects the arguments to be raw ndarrays, while `ms.true_color` works with DataArrays.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Hmm, looks like opening the notebook in VS Code broke something. Looking into it.

**Comment by TomAugspurger** [comment]
OK, should be fixed now: https://nbviewer.jupyter.org/github/microsoft/PlanetaryComputerExamples/blob/1d84d4af6fc2468507c6ba8cad5a5f8d0aa17540/tutorials/cloudless-mosaic-sentinel2.ipynb

**Comment by TomAugspurger** [comment]
To help review, run it yourself: https://pcc-staging.westeurope.cloudapp.azure.com/compute/user/taugspurger@microsoft.com/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPlanetaryComputerExamples&urlpath=lab%2Ftree%2Fpcmosaic%2F&branch=mosaic&targetpath=pcmosaic

(I *think* that link should work).

Note that this requires some packages from staging. I need to deploy prod sometime before merging this.

**Comment by marcozimmermannpm** [comment]
Thanks @TomAugspurger! We'll review it.

**Comment by giancastro** [comment]
@TomAugspurger I think there are some typos, `mosiac` instead of `mosaic`

**Comment by giancastro** [comment]
@TomAugspurger , is something missing at the end of the line?
Screenshot from 2021-05-07 11-50-20

**Comment by giancastro** [comment]
@TomAugspurger , there's raising an error here...
Screenshot from 2021-05-07 11-58-39

`TypeError: Unrecognized STAC collection type <class 'pystac_client.item_collection.ItemCollection'>: <pystac_client.item_collection.ItemCollection object at 0x7f1742157c40>`

**Comment by TomAugspurger** [comment]
Ah, yeah. This is relying on a feature of stacstack that's only available in staging right now, so https://pccompute.westeurope.cloudapp.azure.com/compute/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPlanetaryComputerExamples&urlpath=lab%2Ftree%2Fpcmosaic%2F&branch=mosaic&targetpath=pcmosaic. is the wrong URL. I'll try to deploy prod today.

**Comment by TomAugspurger** [comment]
Just a note that prod is deployed now, so https://pccompute.westeurope.cloudapp.azure.com/compute/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPlanetaryComputerExamples&urlpath=lab%2Ftree%2Fpcmosaic%2F&branch=mosaic&targetpath=pcmosaic should work.

I'm planning to merge this later today. I opened https://github.com/makepath/xarray-spatial/issues/425 to discuss that sub-issue.

**Comment by thuydotm** [comment]
@TomAugspurger thanks, the link above worked for me. I'll look into the sub-issue ASAP.

**Comment by TomAugspurger** [comment]
Great, thanks. https://github.com/makepath/xarray-spatial/issues/425 isn't super high-priority FYI, and isn't a blocker here. Just something to keep in mind (or let me know if I'm missing something obvious).

**Pull request merged**
