### PR TITLE
More MODIS

### PR DESCRIPTION
**Pull request by gadomski**
Opening as draft to wait for @pholleway who has two more notebooks to add. Includes typo fixes for modis vegetation.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks, those look good, I just pushed a couple minor changes for formatting the text and the snow cover plot.

image

LMK when the other ones are ready and we'll get this merged.

**Comment by gadomski** [comment]
Thanks Tom, that's much cleaner. Will do re: ping when others are ready.

**Comment by gadomski** [comment]
@TomAugspurger we've added @pholleway's fire, temp, and reflectance notebooks so should be good for review, thanks!

**Comment by TomAugspurger** [comment]
Thanks @gadomski. I'm not sure why but our CLA bot is claiming you haven't signed the CLA. Can you confirm that you have? https://cla.opensource.microsoft.com/microsoft/PlanetaryComputerExamples?pullRequest=161

**Comment by TomAugspurger** [comment]
Should be all good now. Thanks!

**Pull request merged**
