### PR TITLE
Add reprojection notebook

### PR DESCRIPTION
**Pull request by thuydotm**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
GitHub isn't letting me comment inline, so a few notes:

1. Change imports like `from rasterio.crs import CRS as RioCRS` to just `import rasterio.crs` and use the full name
2. Hide the `<matplotlib.image.AxesImage at ...>` output with a semicolon for plots
3. Hide the axes on the plots, or make the tick labels nicer if they're relevant.
4. The `urls` have SAS tokens in them. They expire quickly, but we still shouldn't have them in the notebook output (`Out[7]`)
5. I think it's worth explicitly stating that these methods only work on datasets that fit in-memory on a single node.
6. https://corteva.github.io/rioxarray/stable/examples/reproject.html has a simpler example of `rioxarray.open_rasterio(...).rio.reproject(...)`, as an alternative to the `WarpedVRT`. Is the motivation for using the `WarpedVRT` to keep the memory footprint down? I wonder if `rioxarray.open_rasterio` would benefit from a `crs` option, to do that in the background.

**Comment by thuydotm** [comment]
Thanks for the comments. 
- 1, 2, 4, 5 are resolved. 
- 3, the axes are relevant as they show coords of the DataArrays. Not sure how it would change at the moment. 
- 6, the idea of using `WarpedVRT` and `stackstac.reproject_array` is to have reprojection work with Dask. But we already call `.compute()` before doing reprojection with `stackstac.reproject_array` though..

**Comment by TomAugspurger** [comment]
One thing that I think is worth explaining here. IIUC, there are four combinations of reprojection that we might consider. They differ by the input (file(s) from disk or a data structure) and the toolchain (rioxarray / rasterio / GDAL vs. stackstack). The 4 are

1. Reproject while loading with rioxarray / rasterio / GDAL using a WarpedVRT:
```python
    with rasterio.open(url) as src:
        with rasterio.vrt.WarpedVRT(src, crs="EPSG:4326") as vrt:
            rds = rioxarray.open_rasterio(vrt)
            rds.sel(band=1).plot.imshow()

```
2. Reproject an *in-memory* DataArray (using something like `.rio.reproject`, `.rio.reproject_match`, `rasterio.warp.reproject`). Unlikely to ever work on a large distributed dataset
```python
xds_lonlat = xds.rio.reproject("EPSG:4326")
```
3. Reproject while loading with stackstack
```python
ds = stackstac.stac(items, epsg=epsg, resolution_xy=..., ...)
```
4. Reproject an in-memory array with stackstac.reproject_array (currently only works on a single-machine, would require some work to scale)
```python
stackstac.reproject_array(arr, spec)
```

---

If the above sounds correct (does it?) then I think we should be able to answer the question "Which one is best?", or at least "Which one should I use when?".

- If possible, it's preferable to do the reprojection *while loading the data* (so option 1 or 3). IIUC this will have a lower memory footprint, and works on large datasets today.
- If you can't do the reprojection while reading (any example why you wouldn't be able to?) then how would you choose between 2 and 4? Just toolchain preference (you're used to GDAL, etc.)?

---

https://nbviewer.jupyter.org/gist/TomAugspurger/9c55691894395f7140249f99b0f05e5f has a notebook exploring options 3 and 4 (stackstac). That links to a neat notebook from Caleb showing a workflow using option 1 (WarpedVRT) with NAIP and NLCD: https://github.com/microsoft/ai4eutils/blob/master/geospatial/notebooks/Example%20-%20Reproject%20NLCD%20to%20NAIP%20tile%20boundaries.ipynb

**Comment by thuydotm** [comment]
Your idea made the story much more seamless and clear, really appreciate it. I've updated the notebook accordingly and we'll release a new version of `xarray-spatial` to update `true_color` function so that user can tune some params to change the contrast and brightness of output image.

**Comment by TomAugspurger** [comment]
Thanks for the update. I realized after posting https://github.com/microsoft/PlanetaryComputerExamples/pull/24#issuecomment-866933726 that stackstac *does* use GDAL. So the two axes to differentiate along are

1. Data source (in-memory vs. while reading from storage). Prefer reprojecting while reading if possible.
2. Scale (single-cog vs. many cogs). Use stackstac if you're working with a large, distributed dataset.

Actually... there's a *third* component: whether or not you have STAC items available. If you don't have STAC items, then `stackstac` isn't an option.

I've pushed an update reflecting that if you could take a look. I add to remove the `th` argument to one of the `true_color` calls, it wasn't available on xrspatial main. I suspect we'll use the same arguments for all the plots once they're available?

**Comment by thuydotm** [comment]
I think reprojecting an in-memory array with `stackstac.reproject_array` does not use GDAL as stated in its [docstring](https://github.com/gjoseph92/stackstac/blob/main/stackstac/geom_utils.py#L219). Only while-loading reprojection uses GDAL I believe.

**Comment by TomAugspurger** [comment]
Ah, you're correct. Thanks for catching that.

**Comment by TomAugspurger** [comment]
Thanks all, looks great!

**Pull request merged**
