### PR TITLE
Added resampling to reprojection notebook

### PR DESCRIPTION
**Pull request by thuydotm**

### CODE REVIEW

**Comment by thuydotm** [comment]
This PR added resampling to the reprojection notebook. @TomAugspurger Can you please take a look?

**Comment by TomAugspurger** [comment]
Thanks for this, and sorry for the delay.

Folding it into the reprojection notebook makes sense. I think it'd be nice to have a a sentence or two at the starting defining resampling. Right  now we have

> You will also learn how to use different resampling algorithms to adjust the raster pixel size.

https://rasterio.readthedocs.io/en/latest/topics/resampling.html has

> Resampling refers to changing the cell values due to changes in the raster cell grid.

I think we should have something about combining pixels, interpolation, etc. in the definition. How about

> Reprojecting data usually also includes resampling the raster data to a different resolution, which requires combining multiple pixel values into (when downsampling -- or resampling to lower resolution/larger cellsizes) or interpolating new pixels from the existing ones (when upsampling -- or  resampling to higher resolution/smaller cells).

**Comment by thuydotm** [comment]
Thanks for your comments, the notebook is updated as suggested.

**Comment by TomAugspurger** [comment]
Force-pushed a commit to remove the change in the kernel display name.

Thanks!

**Pull request merged**
