### PR TITLE
Add DRCOG & CCLC notebooks

### PR DESCRIPTION
**Pull request by pholleway**
- Adds a notebook for DRCOG LULC and Chesapeake. (drcog-lulc)(chesapeake-lu) 

- Notebooks will need to be updated to production API (https://planetarycomputer.microsoft.com/api/stac/v1) at some point.

- VIIRS notebooks not added. I believe the notebook signing api can't access pc-test items.

### CODE REVIEW

**Comment by pholleway** [comment]
Issue with pre-commit. I'll make the fix soon.

**Comment by pholleway** [comment]
cc @gadomski

**Comment by gadomski** [comment]
My only comment is that the two "Displaying the data" sections could use `rich.table` to display the classification values. Otherwise, looks great!

**Comment by pholleway** [comment]
> My only comment is that the two "Displaying the data" sections could use `rich.table` to display the classification values. Otherwise, looks great!

That's a good point. Thanks for taking a look!

**Review by gadomski — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks. I pushed a couple changes:

1. Use `pystac_client.Client` rather than `from pystac import Client`. We also have `dask.distributed.Client`, so I like to fully qualify them.
2. I think that having the class labels in a legend is important for these LULC dataset, so I constructed the plots with matplotlib rather than using the `rendered_preview`. This is still very painful :/

**Comment by pholleway** [comment]
> Thanks. I pushed a couple changes:
> 
> 1. Use `pystac_client.Client` rather than `from pystac import Client`. We also have `dask.distributed.Client`, so I like to fully qualify them.
> 2. I think that having the class labels in a legend is important for these LULC dataset, so I constructed the plots with matplotlib rather than using the `rendered_preview`. This is still very painful :/

Thanks for the feedback and the changes, Tom. I'll use pystac.Client and matplotlib colormaps next time around.

**Pull request merged**
